In [1]:
import csv
import re
import numpy as np
from pandas import *
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [2]:
# Read file
reader = csv.reader(open("Eminem.csv", "r+"), delimiter=",")
# Transform into matrix
full_matrix = list(reader)
# Remove label names
matrix = np.matrix(full_matrix[1:])
# Remove unused columns
matrix = matrix[:, 3:]

In [3]:
# Regex to remove unwanted characters
regex = re.compile('([^\s\w]|_)+')
total_len = 0
for x in matrix[:, 0]:
    x[0, 0] = regex.sub(' ', x[0, 0])
    # Get avg comment length
    total_len += len(x[0])
avg_len = total_len/len(matrix)

In [4]:
# Get a list of the comments
comment_list = matrix[:, 0]
output = np.concatenate(comment_list).ravel().tolist()[0]
# Tokenize
cv = CountVectorizer()
ex = cv.fit_transform(output)
print(ex.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
#print(avg_len)
#print(pandas.DataFrame(matrix))